### ISSUE TITLE
Logging framework

### ISSUE THREAD

**Issue by perlindgren** [perlindgren/syncrim#10]
# Problem

As of now, neither `Vizia` nor `SyncRim` adopts any logging framework. 

We should consider how we want to do this, I don't have any strong personal opinion, so please suggest what You would prefer. 

As we are not bound to `Vizia` (`SyncRim` can run headless, or with `EGui`), we can freely experiment. Maybe adopt the one used by `EGui` (if any)?

**Comment by geom3trik** [comment]
I was planning to add a logging crate to vizia very soon (in the next couple of days), so I'd be interested to hear which one people prefer.

**Comment by perlindgren** [comment]
There is now a PR for vizia adding `fern` as a logging framework, maybe we should follow...?

**Comment by perlindgren** [comment]
Fern logging for the examples has been implemented. So closing issue.
