### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by Freddo3000** [perlindgren/syncrim#35]
There seems to be a pile of old branches that are falling out of date or have already been merged, we should probably clean them up at some point.

**Comment by perlindgren** [comment]
Indeed, I have already removed some. But as you say there a few that are redundant and should be removed.

**Comment by perlindgren** [comment]
I think we now have a (more) reasonable number of branches. So I close this issue for now. If it starts to grow out of hands, please re-open or make a new issue on the topic.
