### ISSUE TITLE
Simulation status

### ISSUE THREAD

**Issue by perlindgren** [perlindgren/syncrim#52]
Problem

As of now evaluating (clock) have no return value. So its not possible for the simulator to know if e.g., a halt condition has been encountered.

Solution

Introducing a return type for the `Component::clock` method.

Something like

```rust
enum Condition {
  Error(String),
  Halt(String),
}
```

And let `clock` return `Result<(),Condition>`, where `Ok(())` indicates that clocking was successful, and `Condition` some type of exception. We can later refine the `Condition` to be more specific if we like but this could work to start out with.

- [x] basics as per PR https://github.com/perlindgren/syncrim/pull/58
- [ ] handling of `Condition` in the simulator, allowing run to halt/error etc.
- [ ] handling of `Condition` and `Simulator` status in `vizia`.
- [ ] handling of `Condition` and `Simulator` status in `egui`.

**Comment by perlindgren** [comment]
PR https://github.com/perlindgren/syncrim/pull/58 should address the basics, and we can work based on that.

**Comment by onsdagens** [comment]
Addressed with #78 .
